const query_egg = new Moralis.Query('Egg')
const query_avatar = new Moralis.Query('Avatar')
const query_user = new Moralis.Query(Moralis.User)
const query_party = new Moralis.Query('Party')
const query_egg_master = new Moralis.Query('EGG_MASTER')